---
title: "git_00"
author: "Evelyn Chairez"
date: "Year 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  
  
“Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Something there is that doesn’t love a wall,  
That sends the frozen-ground-swell under it,  
And spills the upper boulders in the sun;  
And makes gaps even two can pass abreast.  
The work of hunters is another thing:  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Deny me the vision, I perish;  
Rob me of dream and I die;  
Life void of vision and dreaming  
Is life without sun in the sky.  
Oh, blind my rapt eyes in your hatred,  
Submerge me with want and cold care,  
But so long as you leave me my dreaming  
I'll laugh at the demon despair.  
No dungeon was dark enough ever  
To bar me from beauty and light,  
So long as I still have my dreaming,  
My soul will not wander in night.  
So leave me the dream, I beseech you—  
Though it seem but wraithlike and frail—  
For if I be guided by vision,  
I dare against all things prevail.  